version: '2'  

services:
  web:
    image: yougooo/library_app:latest
    command: bash -c "gunicorn ./library/library.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  db:
    image: postgres:latest

