version: '2'  

services:  
  nginx:
    image: nginx:latest
    ports:
      - "8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    command: bash -c "gunicorn ./library/library.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - .:/code
    expose:
      - "8000"

  db:
    image: postgres:latest

