version: '2'  

services:  
  
  nginx:
    image: nginx
    ports:
      - "8001:8001"

  web:
    image: yougooo/library_app 
    command: bash -c "gunicorn --env DJANGO_SETTINGS_MODULE=library.settings.local library.wsgi -b 0.0.0.0:8000"
    ports: 
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: yougooo/library_db
    restart: always
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library

