version: '2'  

services:  
  
  nginx:
    image: nginx
    ports:
      - "8000:8000"
    depends_on:
      - web
    volumes:
      - ./static:/static
      - ./config/nginx:/etc/nginx/conf.d

  web:
    image: yougooo/library_app:latest 
    command: bash -c "gunicorn --env DJANGO_SETTINGS_MODULE=library.settings.local library.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./static:/static

  db:
    image: yougooo/library_db
    restart: always
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library

